# Generated by Django 5.0.3 on 2024-03-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeeX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('deeX', models.TextField(max_length=140)),
                ('slug', models.SlugField()),
                ('time_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
